#!/usr/bin/python3
# -*- coding: utf-8 -*-

class Employee:

    def __init__(self, pay):
        self.pay = pay
        self.money = 0

    def receive_salary(self, much):
        self.money += much

@@q1@@
